const {JSDOM}=require('jsdom');
const fs=require('fs');
const assert=require('assert');
const swift=fs.readFileSync(require('path').join(__dirname, '../../DailyDepth/ReaderView.swift'),'utf8');
const extraction=swift.split('let extraction = #"""')[1].split('"""#')[0];
const prose='Engineering systems need careful evaluation with realistic examples, explicit tradeoffs, and measured performance. '.repeat(12);
const dom=new JSDOM(`<html><head><title>Engineering diagrams</title></head><body><article><h1>Engineering diagrams</h1><p>${prose}</p><p>Before diagram<img src="/figures/inline.png" width="600" height="300" alt="Inline chart">After diagram</p><figure><img data-src="../lazy.webp" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///w==" width="800" height="400" alt="Lazy diagram"><figcaption>Measured latency by configuration.</figcaption></figure><svg viewBox="0 0 400 200" aria-label="System architecture"><rect width="400" height="200" fill="red"/></svg><p>${prose}</p></article></body></html>`,{url:'https://example.com/posts/article',runScripts:'outside-only'});
dom.window.eval(fs.readFileSync(require('path').join(__dirname, '../../DailyDepth/Reader/Readability.js'),'utf8'));
const result=JSON.parse(dom.window.eval(extraction));
const images=result.blocks.filter(b=>b.kind==='image');
assert.equal(images.length,3);
assert.equal(images[0].src,'https://example.com/figures/inline.png');
assert.equal(images[1].src,'https://example.com/lazy.webp');
assert(images[2].src.startsWith('data:image/svg+xml;base64,'));
assert(result.blocks.some(b=>b.kind==='figcaption'&&b.text==='Measured latency by configuration.'));
const first=result.blocks.findIndex(b=>b.kind==='image');
assert.equal(result.blocks[first-1].text,'Before diagram');
assert.equal(result.blocks[first+1].text,'After diagram');
console.log('PASS: inline image order, relative URLs, lazy source, caption, SVG preservation.');
const rich=new JSDOM(`<html><head><title>Rich article</title></head><body><article><h1>Rich article</h1><p>${prose}</p><p>A <strong>bold <em>nested emphasis</em></strong>, <code>some_code()</code>, <a href="../guide#section">relative link</a>, <s>old</s>, x<sup>2</sup><br>new line <a href="javascript:alert(1)">unsafe</a>.</p><ol start="3"><li>First item</li><li>Second item</li></ol><p>${prose}</p></article></body></html>`,{url:'https://example.com/posts/article',runScripts:'outside-only'});
rich.window.eval(fs.readFileSync(require('path').join(__dirname, '../../DailyDepth/Reader/Readability.js'),'utf8'));
const blocks=JSON.parse(rich.window.eval(extraction)).blocks;
const runs=blocks.flatMap(b=>b.runs||[]);
assert(runs.some(r=>r.text==='nested emphasis'&&r.bold&&r.italic));
assert(runs.some(r=>r.code&&r.text==='some_code()'));
assert(runs.some(r=>r.link==='https://example.com/guide#section'));
assert(!runs.some(r=>r.link?.startsWith('javascript:')));
assert(runs.some(r=>r.strike));
assert(runs.some(r=>r.baseline===1));
assert(runs.some(r=>r.text==='\n'));
assert(blocks.some(b=>b.kind==='li'&&b.marker==='3.'));
for(const block of blocks) if(block.runs) assert.equal(block.text,block.runs.map(r=>r.text).join(''));
console.log('PASS: nested formatting, code, links, unsafe schemes, strike, superscript, line breaks, list numbering, selection text.');
function dateFixture(head) {
 const page=new JSDOM(`<html><head><title>Dated article</title>${head}</head><body><article><h1>Dated article</h1><p>${prose}</p><p>${prose}</p></article></body></html>`,{url:'https://example.com/article',runScripts:'outside-only'});
 page.window.eval(fs.readFileSync(require('path').join(__dirname, '../../DailyDepth/Reader/Readability.js'),'utf8'));
 return JSON.parse(page.window.eval(extraction)).published;
}
assert.equal(dateFixture('<meta property="article:published_time" content="2024-02-11T10:00:00Z">'),'2024-02-11T10:00:00Z');
assert.equal(dateFixture('<script type="application/ld+json">{"@graph":[{"@type":"BlogPosting","datePublished":"2025-04-03","dateModified":"2026-01-01"}]}</script>'),'2025-04-03');
assert.equal(dateFixture('<meta property="article:modified_time" content="2026-01-01">'),null);
console.log('PASS: publication metadata and JSON-LD extraction; modified date is not substituted for publication date.');
